/**
 * GET /api/commentary/manifest/:matchId/:lang
 *
 * Returns the JSON manifest of pre-rendered commentary lines for a
 * given match + language.
 *
 * Phase-3 stub: the actual MP3 corpus is generated by an offline
 * pipeline that doesn't exist yet (it's the ElevenLabs batch step
 * that runs once per match). Until that lands the route returns an
 * empty `lines: []` manifest, the client treats that as "no
 * pre-rendered audio yet, fall back to live WSS commentary if a key
 * is configured".
 *
 * Cache: `s-maxage=300, stale-while-revalidate=86400` per
 * `docs/27c-fidelity-phase3-stadium-crowd.md` § "Caching".
 */

import { NextResponse } from "next/server";

export const dynamic = "force-static";
export const runtime = "nodejs";

export async function GET(
  _req: Request,
  props: { params: Promise<{ matchId: string; lang: string }> }
): Promise<NextResponse> {
  const params = await props.params;
  return NextResponse.json(
    {
      match: params.matchId,
      lang: params.lang,
      lines: [],
    },
    {
      headers: {
        "Cache-Control":
          "public, s-maxage=300, stale-while-revalidate=86400",
      },
    },
  );
}
