/**
 * Player data accessors backed by `apps/web/data/players-2026.json`.
 *
 * The dataset is generated by
 * `pnpm --filter @vtorn/wc2026-data-scripts run scrape-players`. It's
 * shipped as a static JSON in the web app so server-rendered player pages
 * have zero data dependencies at runtime.
 *
 * All helpers are pure + synchronous. Consumed by:
 *   - `app/player/[id]/page.tsx`
 *   - `app/players/page.tsx`
 *   - `app/team/[code]/page.tsx` (squad grid replacement)
 *   - the vitest suite directly
 */

import dataset from "@/data/players-2026.json";

// ---------- types (kept local; mirror @vtorn/wc2026-data-scripts) ----------

export type PlayerPosition = "GK" | "DEF" | "MID" | "FWD";

export interface PlayerRecord {
  readonly id: string;
  readonly wikidataQid: string;
  readonly name: string;
  readonly fullName?: string | null;
  readonly code: string;
  readonly shirtNumber?: number | null;
  readonly position: PlayerPosition;
  readonly dob?: string | null;
  readonly club?: string | null;
  readonly clubLogo?: string | null;
  readonly imageUrl?: string | null;
  readonly imageCredit?: string | null;
  readonly imageLicence?: string | null;
  readonly captain?: boolean;
  readonly wikipediaUrl?: string | null;
}

export interface PlayerDataset {
  readonly version: number;
  readonly lastUpdated: string;
  readonly source: "wikidata" | "seed" | "mock";
  readonly players: readonly PlayerRecord[];
}

// ---------- typed dataset access ----------

const TYPED_DATASET = dataset as unknown as PlayerDataset;

export function allPlayers(): readonly PlayerRecord[] {
  return TYPED_DATASET.players;
}

const BY_ID: ReadonlyMap<string, PlayerRecord> = (() => {
  const m = new Map<string, PlayerRecord>();
  for (const p of TYPED_DATASET.players) m.set(p.id, p);
  return m;
})();

const BY_CODE: ReadonlyMap<string, readonly PlayerRecord[]> = (() => {
  const m = new Map<string, PlayerRecord[]>();
  for (const p of TYPED_DATASET.players) {
    const arr = m.get(p.code) ?? [];
    arr.push(p);
    m.set(p.code, arr);
  }
  // Stable ordering: GK first, then DEF, MID, FWD; tiebreak by shirt number.
  const order: Record<PlayerPosition, number> = { GK: 0, DEF: 1, MID: 2, FWD: 3 };
  for (const arr of m.values()) {
    arr.sort((a, b) => {
      const dp = order[a.position] - order[b.position];
      if (dp !== 0) return dp;
      const an = a.shirtNumber ?? 99;
      const bn = b.shirtNumber ?? 99;
      return an - bn;
    });
  }
  return m;
})();

export function findPlayer(id: string): PlayerRecord | undefined {
  return BY_ID.get(id.toUpperCase());
}

export function playersForTeam(code: string): readonly PlayerRecord[] {
  return BY_CODE.get(code.toUpperCase()) ?? [];
}

export function allPlayerIds(): readonly string[] {
  return TYPED_DATASET.players.map((p) => p.id);
}

// ---------- search + filter (pure) ----------

export interface PlayerSearchOpts {
  readonly q?: string;
  readonly code?: string;
  readonly position?: PlayerPosition | "ALL";
  readonly club?: string;
}

/**
 * Filter the full player list by free-text query (matches name, fullName,
 * code, club), team code, position, and/or club name. All filters are
 * AND-combined. Empty strings are treated as "no filter".
 */
export function searchPlayers(
  opts: PlayerSearchOpts,
  source: readonly PlayerRecord[] = TYPED_DATASET.players,
): readonly PlayerRecord[] {
  const q = (opts.q ?? "").trim().toLowerCase();
  const code = (opts.code ?? "").trim().toUpperCase();
  const club = (opts.club ?? "").trim().toLowerCase();
  const pos = opts.position && opts.position !== "ALL" ? opts.position : null;
  return source.filter((p) => {
    if (q) {
      const hay = [
        p.name,
        p.fullName ?? "",
        p.code,
        p.club ?? "",
      ]
        .join(" ")
        .toLowerCase();
      if (!hay.includes(q)) return false;
    }
    if (code && p.code !== code) return false;
    if (pos && p.position !== pos) return false;
    if (club && !((p.club ?? "").toLowerCase().includes(club))) return false;
    return true;
  });
}

// ---------- derived helpers ----------

export function ageOnDate(dob: string | null | undefined, refIso: string): number | null {
  if (!dob) return null;
  const d = Date.parse(dob);
  const r = Date.parse(refIso);
  if (!Number.isFinite(d) || !Number.isFinite(r)) return null;
  const ms = r - d;
  if (ms < 0) return null;
  // 365.2425 days/year, close enough for display.
  const years = ms / (1000 * 60 * 60 * 24 * 365.2425);
  return Math.floor(years);
}

export const POSITION_LABEL: Record<PlayerPosition, string> = {
  GK: "Goalkeeper",
  DEF: "Defender",
  MID: "Midfielder",
  FWD: "Forward",
};

/** Distinct list of clubs in the dataset, sorted alphabetically. */
export function distinctClubs(): readonly string[] {
  const s = new Set<string>();
  for (const p of TYPED_DATASET.players) {
    if (p.club) s.add(p.club);
  }
  return [...s].sort((a, b) => a.localeCompare(b));
}

/** Distinct list of team codes in the dataset, sorted alphabetically. */
export function distinctCodes(): readonly string[] {
  const s = new Set<string>();
  for (const p of TYPED_DATASET.players) s.add(p.code);
  return [...s].sort();
}

export function datasetMeta(): { readonly source: PlayerDataset["source"]; readonly lastUpdated: string; readonly count: number } {
  return {
    source: TYPED_DATASET.source,
    lastUpdated: TYPED_DATASET.lastUpdated,
    count: TYPED_DATASET.players.length,
  };
}
