#!/usr/bin/env bash
# tools/daily-report-cron.sh
#
# Tournamental daily-progress-report cron wrapper.
#
# What it does:
#   1. Resolves the repo root from this script's location.
#   2. Pulls latest main + rebases.
#   3. Picks the report date (CLI arg `--date=YYYY-MM-DD`, or yesterday UTC
#      so a `0 8 * * *` cron run summarises the previous calendar day).
#   4. Runs `pnpm --filter @vtorn/tools daily-report -- --date=<date>`,
#      writing `sessions/daily/<date>.md`.
#   5. Creates branch `daily-report/<date>`, commits the markdown
#      (signed, conventional), pushes, and opens a PR ready for the
#      orchestrator to merge.
#
# Recommended cron line (run at 08:00 UTC, summarising yesterday):
#
#   0 8 * * * /home/clawdbot/clawdia/projects/vtorn/tools/daily-report-cron.sh \
#     >> /var/log/vtorn-daily-report.log 2>&1
#
# Exit codes:
#   0  success (or no-op if the branch already exists with no new content)
#   1  hard failure (lint/test failed, push failed, etc.)
#
# This script is intentionally short — the heavy lifting lives in the
# typed `daily-report.ts`. The cron wrapper only owns the git surface.

set -euo pipefail

# --- Resolve paths --------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# --- Pick the date --------------------------------------------------------
REPORT_DATE=""
for arg in "$@"; do
  case "$arg" in
    --date=*) REPORT_DATE="${arg#--date=}" ;;
    --help|-h)
      sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
  esac
done
if [[ -z "$REPORT_DATE" ]]; then
  REPORT_DATE="$(date -u -d 'yesterday' +%Y-%m-%d)"
fi
echo "[daily-report-cron] date=$REPORT_DATE repo=$REPO_ROOT"

# --- Sync main ------------------------------------------------------------
git fetch origin --prune
git checkout main
git pull --rebase origin main

# --- Run the generator ----------------------------------------------------
pnpm --filter @vtorn/tools install --silent || true
pnpm --filter @vtorn/tools run daily-report -- --date="$REPORT_DATE"

REPORT_PATH="sessions/daily/$REPORT_DATE.md"
if [[ ! -f "$REPORT_PATH" ]]; then
  echo "[daily-report-cron] expected $REPORT_PATH; aborting" >&2
  exit 1
fi

# --- Stage + branch + commit ---------------------------------------------
BRANCH="daily-report/$REPORT_DATE"

# If the branch already exists locally, reset to main; remote-side is fine.
if git show-ref --quiet "refs/heads/$BRANCH"; then
  git branch -D "$BRANCH"
fi
git checkout -b "$BRANCH"

git add "$REPORT_PATH"
if git diff --cached --quiet; then
  echo "[daily-report-cron] no changes to commit; exiting cleanly"
  exit 0
fi

git -c user.email='0800tim@gmail.com' -c user.name='daily-report-bot' \
  commit -s -m "docs(daily): $REPORT_DATE progress report

Auto-generated by tools/daily-report.ts.

Refs: tools/daily-report.ts
"

# --- Push + open PR -------------------------------------------------------
git push -u origin "$BRANCH"

if command -v gh >/dev/null 2>&1; then
  gh pr create \
    --base main \
    --head "$BRANCH" \
    --title "docs(daily): $REPORT_DATE progress report" \
    --body "Auto-generated daily progress report for **$REPORT_DATE**.

Sources:
- \`git log\` between 00:00 and 23:59 UTC of $REPORT_DATE
- Workspace inventory across \`apps/*\` and \`packages/*\`
- \`pnpm test --run --reporter=basic\` summary
- \`gh pr list --state open\` snapshot

Re-runs of the generator append an \"Update appended at\" section
rather than overwriting, so the orchestrator can hand-edit safely.

Refs: tools/daily-report.ts" \
    --label "automation" || \
  echo "[daily-report-cron] gh pr create failed (PR may already exist)"
else
  echo "[daily-report-cron] gh CLI not installed; pushed branch $BRANCH for manual PR"
fi

echo "[daily-report-cron] done"
