-- 0015_swarm_summary.sql , operator-keyed aggregate summaries published
-- by each swarm operator (browser tab at /run, Node operator running
-- @tournamental/bot-node, or any custom client).
--
-- One row per (operator_id, kickoff_at). Idempotent: re-POSTing the
-- same payload for the same kickoff overwrites the prior row so a
-- recovering client can re-publish after a transient network failure
-- without duplicating leaderboard entries.
--
-- Why a separate table from `swarm_claims` (0014):
--   - swarm_claims is per-run, OTS-anchored, and captures a single
--     best-bot claim. It exists to support the public verifiability
--     story (one merkle root → one OTS proof → one cross-swarm rank).
--   - swarm_summary is per-operator, periodic, and captures the FULL
--     aggregate (total bots ever generated, alive count by match
--     number, top-1000 leaderboard within the swarm). It exists so
--     viewers of an operator's profile get a cheap downloadable JSON
--     of their swarm aggregates, and so the perfect-track watcher can
--     surface "N bots still alive after match 80" on the home page.
--
-- Spec: A13 task brief (operator publish endpoint + perfect-track watch).
--
-- Cache strategy: GET /v1/swarms/<operator_id> is served with
-- Cache-Control: public, s-maxage=60, stale-while-revalidate=300 so
-- Cloudflare's edge holds the JSON between origin polls.

CREATE TABLE IF NOT EXISTS swarm_summary (
  -- The operator_id is the sha256 hash of the operator's API key
  -- (matches api_key.key_hash). One hash per operator means the
  -- profile aggregate naturally rolls up everything posted under
  -- that key without inventing a second identity column.
  operator_id        TEXT NOT NULL,
  -- ms-epoch of the kickoff this snapshot is aligned to. Combined
  -- with operator_id this is the idempotency key for re-POSTs.
  kickoff_at         INTEGER NOT NULL,
  -- Cumulative count of bots ever generated by this operator.
  total_bots         INTEGER NOT NULL,
  -- JSON array of { n: number, alive_count: number }, one row per
  -- resolved match. n is the 1-indexed match ordinal in the
  -- canonical fixture order.
  alive_by_match_json TEXT NOT NULL DEFAULT '[]',
  -- 0..104 , highest match-count any bot in this swarm has nailed.
  best_bot_score     INTEGER NOT NULL DEFAULT 0,
  -- JSON array of { bot_id, score, chalk_score } sorted by score
  -- desc. Up to 1,000 rows.
  top_k_json         TEXT NOT NULL DEFAULT '[]',
  -- 64-char lower-hex sha256 of the latest batch's merkle root.
  merkle_root        TEXT NOT NULL DEFAULT '',
  generated_at       INTEGER NOT NULL,
  PRIMARY KEY (operator_id, kickoff_at)
);

CREATE INDEX IF NOT EXISTS idx_swarm_summary_operator_kickoff
  ON swarm_summary(operator_id, kickoff_at DESC);

-- Best-score index lets the global aggregate leaderboard scan the
-- top 100 in O(log n).
CREATE INDEX IF NOT EXISTS idx_swarm_summary_best_score
  ON swarm_summary(best_bot_score DESC);

-- Perfect-track alert table. One row per operator that crossed the
-- match-80 threshold with bots still alive. The home page + the
-- /leaderboard badge poll this table to surface "N bots still on a
-- perfect track after match X".
CREATE TABLE IF NOT EXISTS perfect_track_alert (
  operator_id        TEXT NOT NULL,
  match_number       INTEGER NOT NULL,
  alive_count        INTEGER NOT NULL,
  detected_at        INTEGER NOT NULL,
  PRIMARY KEY (operator_id, match_number)
);

CREATE INDEX IF NOT EXISTS idx_perfect_track_alert_match
  ON perfect_track_alert(match_number DESC, alive_count DESC);
